### ISSUE TITLE
config: need some explanation

### ISSUE THREAD

**Issue by xberg** [nan0s7/nfancurve#10]
Hi,
You have the following text in the config file, and the subsequent array:
by default it's set up so that when the temp is less than or equal to 30
degrees, the fan speed will be set to 20%. next, if the temp is between 31
and 40, the fan speed should be set to 35%, etc.
he last temperature value will be the maximum temperature before 100% fan
speed will be set
you can make the array as big or as small as you require, as long as they
both end up being the same size
declare -a fcurve=( "25" "40" "55" "70" "85" )
declare -a tcurve=( "35" "45" "55" "65" "75" )

This does not make sense to me. Where is: 
- "when the temp is less than or equal to 30" : I don't see any 30 in this array
- "the fan speed will be set to 20%": again where is this 20?

What is should probably be saying is:
When the temp is less than or equal to 25 the fan speed will be set to 35%
or is it the other way round?

**Comment by xberg** [comment]
OK, now that I fixed multi GPU it's clear that the first line is fan speed and the second is temperature. Perhaps you could add that clearly in the config explanation? 
It's now obvious to me because of the variable names :) Silly me...

**Comment by nan0s7** [comment]
Yeah that's my mistake. I changed the default values for `fcurve` and `tcurve` but didn't update the description... but it's all good now :)
