### ISSUE TITLE
Only one fan of three detected

### ISSUE THREAD

**Issue by Athlan88** [nan0s7/nfancurve#30]
Hi!

The script only detects 1 of 3 GPU fans:
`onfiguration file: /home/aaron/nfancurve/config
Number of Fans detected: 
1
Number of GPUs detected: 
1
`
GPU is Nvidia GTX 1080.

What is wrong?

**Comment by nan0s7** [comment]
Are all three fans working reguardless? My script only uses the information given to it by the `nvidia-smi` command; so it will only detect the fan controllers (which can control multiple fans - my GPU, the 1070, has two fans and only one controller, so when I run my script it says the same as yours).

**Comment by Athlan88** [comment]
Is there any way to tell except from opening the PC? Unfortunately I am not able to do this.

**Comment by nan0s7** [comment]
Hmm if you know the model of your GPU you can Google it. You can try looking through the `nvidia-smi` command/interface; check that any fans it detects are running at the proper speeds. If the temperatures are good and it shows that the fans are running properly, then there's no reason to believe what my script detected is wrong.

**Comment by Athlan88** [comment]
I get this response: 
`Thu Apr 30 13:58:40 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
| 40%   35C    P0    44W / 270W |    321MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       764      G   /usr/lib/Xorg                                208MiB |
|    0      1096      G   /usr/bin/kwin_x11                             45MiB |
|    0      1102      G   /usr/bin/plasmashell                          61MiB |
+-----------------------------------------------------------------------------+
`
I can hear the fans spinning and the temperature is at 35°C, which is good. I think it works correctly, although I cannot tell if really all three fans spin or not.

**Comment by nan0s7** [comment]
Well it seems to me that they're working. No reason to believe the fans aren't all being controlled by the script unless you can look inside the computer or the temperatures are incorrect. :)
