### ISSUE TITLE
systemd service fails to start

### ISSUE THREAD

**Issue by Zlendy** [nan0s7/nfancurve#38]
Hi!
I've used this script for a few weeks and so far it has worked really well. However, after a recent update of the nvidia drivers for arch linux the script is no longer working and the error code isn't really helpful.
I'm going to try to force the downgrade of the drivers after submitting this issue, if the error persists then I messed up somehow.
This is the output of the command `systemctl status --user nfancurve`

Thanks in advance!

![image](https://user-images.githubusercontent.com/22578704/103910763-80a64a00-5105-11eb-8deb-5ae6988c5854.png)

**Comment by nan0s7** [comment]
Hey! Sorry for the delay; let me know if the issue persists in the next update. I'm a bit busy to test it myself right now, but I should be able to patch it if it's a common thing. :)

**Comment by Zlendy** [comment]
Hi, I you've probably not updated nfancurve yet. I just want to let you know that after some upgrades to my system I've decided to test if nfancurve works again and it does now. I have no idea what caused it to fail in the first place. Sorry for any inconvenience, I'll let you know if I experience any other bugs as soon as possible.

**Comment by nan0s7** [comment]
Thanks for letting me know you had a problem! Glad to hear it's working fine now :)
