### ISSUE TITLE
Could you please create a new release ?

### ISSUE THREAD

**Issue by HanM23** [nan0s7/nfancurve#49]
Hi,

Thanks for your software, i use it and i like it.

Could you please create a new release with the latest commits ? So that @ReneHollander can create a new package.

You can see also this in the comments on AUR : https://aur.archlinux.org/packages/nfancurve

Regards

**Comment by nan0s7** [comment]
My apologies for only getting around to this now. Apparently GitHub decided to not send me any update emails. I have now created a new sub-release that fixes a few minor things for the AUR.

**Comment by HanM23** [comment]
Thanks
